version: '2'
services:
  mydb:
    image: mysql:5.6.34
    environment:
      MYSQL_DATABASE: "mydb"
      MYSQL_ROOT_PASSWORD: "wopniep"
      MYSQL_USER: "ninjav"
      MYSQL_PASSWORD: "sunofabitch"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
